api_platform:
    # @Todo : For now use version 2.5 of Api-platform
    # Upgrade Api-platform to version 2.6 with OpenApiInterface exemple here (depreciation of Swagger and use OpenApi) :
    # https://api-platform.com/docs/core/jwt/#adding-endpoint-to-swaggerui-to-retrieve-a-jwt-token

    # The title of the API.
    title: "API title"

    # The description of the API.
    description: "API description"

    # The version of the API.
    version: "1.0.0"

    # @Todo : Create the contact page, the terms of service page and the licence page
    # openapi:
    #     # The contact information for the exposed API.
    #     contact:
    #         # The identifying name of the contact person/organization.
    #         name: '%env(resolve:ADMIN_URL)%'
    #         # The URL pointing to the contact information. MUST be in the format of a URL.
    #         url: '%env(resolve:ADMIN_URL)%'
    #         # The email address of the contact person/organization. MUST be in the format of an email address.
    #         email: '%env(resolve:MAILER_USER)%'
    #     # A URL to the Terms of Service for the API. MUST be in the format of a URL.
    #     termsOfService: '%env(resolve:ADMIN_URL)%'
    #     # The license information for the exposed API.
    #     license:
    #         # The license name used for the API.
    #         name: Licence
    #         # URL to the license used for the API. MUST be in the format of a URL.
    #         url: '%env(resolve:ADMIN_URL)%'

    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]

    patch_formats:
        json: ["application/merge-patch+json"]

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    # Enable the data collector and the WebProfilerBundle integration.
    enable_profiler: true

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    # Enable ReDoc.
    enable_re_doc: true

    # Enable the entrypoint => Disable url /api by default, you need to use /api/docs to see documentation
    enable_entrypoint: false

    # Enable the docs.
    enable_docs: true

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: ["application/ld+json"]

        json:
            mime_types: ["application/json"]

        html:
            mime_types: ["text/html"]

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ["application/problem+json"]

        jsonld:
            mime_types: ["application/ld+json"]
