# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: "%kernel.project_dir%/public/uploads"
        shop_adapter:
            local:
                location: "%kernel.project_dir%/uploads/clients/shop"
    filesystems:
        default_filesystem:
            adapter: default_adapter
            mount: default_filesystem
        shop_filesystem:
            adapter: shop_adapter
            mount: shop_filesystem

