vich_uploader:
    db_driver: orm

    mappings:
        # @Todo :Add upload shop system
        shop_upload:
            uri_prefix: /upload/shop
            upload_destination: '%kernel.project_dir%/datas/upload/shop'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            