# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            - "../src/Tests/"

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller/"
        tags: ["controller.service_arguments"]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #  You must add your api-platform service here

    ##########################################################
    ###### SWAGGER CUSTOM DECORATOR MUST BE DEFINE HERE ######
    ##########################################################

    # Add Swagger components
    App\OpenApi\ComponentsOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false

    # Register new User and get JWT token
    App\OpenApi\Auth\RegisterOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false

    # Logout the current User
    App\OpenApi\Auth\LogoutOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false

    # Add JWT token User auth for api
    App\OpenApi\Auth\AuthenticationTokenOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false

    # Get Refresh JWT token User auth for api
    App\OpenApi\Auth\RefreshTokenOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false

    # Send request to get secret and token
    App\OpenApi\Auth\ResetPassword\SendResetPasswordOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false
    
    # Check secret and token for reset password
    App\OpenApi\Auth\ResetPassword\CheckResetPasswordOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false
    
    # Reset password with valid token auth
    App\OpenApi\Auth\ResetPassword\ResetPasswordOpenApiDecorator:
        decorates: "api_platform.openapi.factory"
        autoconfigure: false

imports:
    - { resource: "services_custom.yaml" } # Custom services
