parameters:
    locale: "%env(resolve:APP_LOCALE)%" # Default LOCALE LANGUAGE value
    mailer_user: "%env(resolve:MAILER_USER)%" # Default MAIL value

    router.request_context.scheme: "%env(API_ENTRYPOINT_SCHEME)%"
    router.request_context.host: "%env(API_ENTRYPOINT_HOST)%"
    request_listener.https_port: "%env(int:API_ENTRYPOINT_PORT)%"

    ### CUSTOM VALUE NOT PRESENT IN .env ###

    # URL for AdminDashboard
    url_for_admin: admin # Define default URL for AdminDashboard

    # Security user impersonation
    route_for_switch_user: _switch_user # Define the switch user route

    # Activation of email confirmation for User
    active_confirm_user: true # Confirmation User email (if false you don't need to confirm User email)

    # Logger for admin connection
    admin.log.register_in_database: true # Enable/Disable register in database logger when an Admin connect to back-office
    admin.log.register_failure_in_database: true # Enable/Disable failure logger in database

    # Logger for admin Update/create/delete CRUD entity
    admin.log.persist_actions_entity: true # Enable/Disable Entity CRUD Actions

services:
    ########################
    ### Mailer Component ###
    ########################

    # Service email notifications for Admin
    app.service.admin_mailer:
        class: App\Service\Admin\Email\AdminMailer
        arguments:
            [
                "@mailer.mailer",
                "@parameter_bag",
                "@doctrine.orm.default_entity_manager",
            ]

    #########################
    ### JWT Refresh Token ###
    #########################

    # Override RefreshTokenManager
    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class: App\Doctrine\RefreshTokenManager
        arguments:
            [
                "@doctrine.orm.default_entity_manager",
                'App\Entity\Customer\UserToken',
            ]

    ########################
    ### VichUploadBundle ###
    ########################

    # Custom Namer for VichUploadBundle
    app.service.upload.client_unique_namer:
        class: App\Service\Admin\Upload\UniqueShopNamer
        public: true

    # Custom Directory Name for VichUploadBundle
    app.service.upload.client_unique_directory_namer:
        class: App\Service\Admin\Upload\UniqueShopDirectoryNamer
        public: true

    #######################
    #### MonologBundle ####
    #######################

    # Admin log
    app.service.admin.log.admin_logger:
        class: App\Service\Admin\Log\AdminLogger
        arguments:
            [
                "@monolog.logger.admin",
                "@doctrine.orm.entity_manager",
                "@request_stack",
                "@security.helper",
            ]
