api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/auth/login_check
    methods: ["POST"]

gesdinet_jwt_refresh_token:
    path: /api/auth/refresh_token
    controller: gesdinet.jwtrefreshtoken::refresh
